# Generated by Django 5.0.7 on 2024-07-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='event_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='eventdata',
            old_name='event_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='event_details',
        ),
        migrations.AddField(
            model_name='eventdata',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
