# Generated by Django 5.0.7 on 2024-07-19 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0002_rename_event_date_eventdata_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventdata',
            old_name='title',
            new_name='event',
        ),
        migrations.RemoveField(
            model_name='eventdata',
            name='description',
        ),
    ]
