# Generated by Django 5.0.7 on 2024-07-19 14:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventdata', '0003_rename_title_eventdata_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='event',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
